steps:
  # Install dependencies
  - name: "node:18"
    entrypoint: npm
    args: ["ci", "--quiet", "--no-fund", "--no-audit"]
    env:
      - "NODE_ENV=development"

  # Build the application with environment variables
  - name: "node:18"
    entrypoint: npm
    args: ["run", "build"]
    env:
      - "REACT_APP_CURRENCY_API_KEY=${_CURRENCY_API_KEY}"
      - "REACT_APP_FIREBASE_API_KEY=${_FIREBASE_API_KEY}"
      - "REACT_APP_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}"
      - "REACT_APP_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}"
      - "REACT_APP_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}"
      - "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}"
      - "REACT_APP_FIREBASE_APP_ID=${_FIREBASE_APP_ID}"
      - "REACT_APP_FIREBASE_MEASUREMENT_ID=${_FIREBASE_MEASUREMENT_ID}"

  # Deploy to Google Cloud Storage
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["-m", "rsync", "-r", "-d", "build/", "gs://${_BUCKET_NAME}/"]

# Optional: Set the build timeout
timeout: "10m"

# Substitution variables (set these in Google Cloud Build)
substitutions:
  _CURRENCY_API_KEY: ""
  _FIREBASE_API_KEY: ""
  _FIREBASE_AUTH_DOMAIN: ""
  _FIREBASE_PROJECT_ID: ""
  _FIREBASE_STORAGE_BUCKET: ""
  _FIREBASE_MESSAGING_SENDER_ID: ""
  _FIREBASE_APP_ID: ""
  _FIREBASE_MEASUREMENT_ID: ""
  _BUCKET_NAME: ""
