name: Deploy to Firebase

on:
  push:
    branches: [ main, firebase-prep ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Verify build output
        run: |
          echo "Checking build directory contents:"
          ls -la build/
          echo "Checking if index.html exists:"
          test -f build/index.html && echo "✅ index.html found" || echo "❌ index.html not found"

      - name: Deploy to Firebase
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/firebase-prep'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: react-portfolio-9f9fd
          channelId: live 